# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

 name: Global
     on:
        push:
        branches: [ "main" ]
    jobs: # Corregido: 'jobs' en minúscula
      platzi:
        runs-on: ubuntu-latest # Corregido: dos puntos estándar
        steps:
        - name: 'Hello World'
        run: echo "Hello World"
